name: CI/CD for FastAPI on AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t fastapi-app .

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push to ECR
      env:
        ECR_REGISTRY: <tu-id-ecr>.dkr.ecr.<tu-region>.amazonaws.com
        ECR_REPOSITORY: fastapi-app
        IMAGE_TAG: latest
      run: |
        docker tag fastapi-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: fastapi-lambda
        aws-region: <tu-region>
        docker-image-uri: <tu-id-ecr>.dkr.ecr.<tu-region>.amazonaws.com/fastapi-app:latest
        role: <tu-rol-lambda>
