name: CI/CD for FastAPI on AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deployment/requirements.txt

    - name: Run model validation
      run: |
        python testing/model_test.py

    - name: Validate model accuracy
      run: |
        accuracy=$(cat testing/accuracy.txt)
        echo "Model accuracy is $accuracy"
        if (( $(echo "$accuracy < 0.8" | bc -l) )); then
          echo "Model accuracy is below 0.8, stopping deployment."
          exit 1
        else
          echo "Model accuracy is acceptable."
        fi

  deploy:
    needs: test_model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deployment/requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t bancolombia deployment/

    - name: Build and Push to ECR
      env:
        ECR_REGISTRY: 646932767172.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: bancolombia
        IMAGE_TAG: latest
      run: |
        docker tag bancolombia:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to AWS Lambda using AWS CLI
      run: |
        aws lambda update-function-code \
          --function-name bancolombia \
          --image-uri 646932767172.dkr.ecr.us-east-1.amazonaws.com/bancolombia:latest
